[tool.poetry]
name = "python-project-49"
version = "0.1.0"
description = "python brain games package"
authors = ["Dmitriy Frolov <omgoole@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
